export const universities: string[] = [
  // Indonesian Universities
  "Universitas Indonesia",
  "Institut Teknologi Bandung",
  "Universitas Gadjah Mada",
  "Institut Pertanian Bogor",
  "Universitas Airlangga",
  "Institut Teknologi Sepuluh Nopember",
  "Universitas Brawijaya",
  "Universitas Diponegoro",
  "Universitas Padjadjaran",
  "Universitas Hasanuddin",
  "Universitas Sebelas Maret",
  "Universitas Negeri Yogyakarta",
  "Universitas Negeri Malang",
  "Universitas Negeri Semarang",
  "Universitas Negeri Jakarta",
  "Universitas Negeri Surabaya",
  "Universitas Negeri Medan",
  "Universitas Negeri Makassar",
  "Universitas Negeri Padang",
  "Universitas Lampung",
  "Universitas Sriwijaya",
  "Universitas Riau",
  "Universitas Sumatera Utara",
  "Universitas Andalas",
  "Universitas Mataram",
  "Universitas Udayana",
  "Universitas Nusa Cendana",
  "Universitas Mulawarman",
  "Universitas Tanjungpura",
  "Universitas Lambung Mangkurat",
  "Universitas Palangka Raya",
  "Universitas Sam Ratulangi",
  "Universitas Tadulako",
  "Universitas Halu Oleo",
  "Universitas Pattimura",
  "Universitas Cenderawasih",
  "Universitas Papua",
  "Universitas Jember",
  "Universitas Jenderal Soedirman",
  "Universitas Tidar",
  "Universitas Siliwangi",
  "Universitas Singaperbangsa Karawang",
  "Universitas Sultan Ageng Tirtayasa",
  "Universitas Pembangunan Nasional Veteran Jakarta",
  "Universitas Pembangunan Nasional Veteran Yogyakarta",
  "Universitas Pembangunan Nasional Veteran Jawa Timur",
  "Universitas Telkom",
  "Universitas Mercu Buana",
  "Universitas Trisakti",
  "Universitas Tarumanagara",
  "Universitas Atmajaya Yogyakarta",
  "Universitas Atmajaya Jakarta",
  "Universitas Sanata Dharma",
  "Universitas Kristen Petra",
  "Universitas Kristen Satya Wacana",
  "Universitas Kristen Indonesia",
  "Universitas Katolik Indonesia Atma Jaya",
  "Universitas Katolik Parahyangan",
  "Universitas Katolik Widya Mandala Surabaya",
  "Universitas Bina Nusantara",
  "Universitas Multimedia Nusantara",
  "Universitas Prasetiya Mulya",
  "Universitas Pelita Harapan",
  "Universitas Ciputra Surabaya",
  "Universitas Surabaya",
  "Universitas Kristen Maranatha",
  "Universitas Komputer Indonesia",
  "Universitas Widyatama",
  "Universitas Pasundan",
  "Universitas Islam Negeri Syarif Hidayatullah Jakarta",
  "Universitas Islam Negeri Sunan Kalijaga Yogyakarta",
  "Universitas Islam Negeri Maulana Malik Ibrahim Malang",
  "Universitas Islam Negeri Sunan Ampel Surabaya",
  "Universitas Islam Negeri Walisongo Semarang",
  "Universitas Islam Negeri Alauddin Makassar",
  "Universitas Islam Negeri Raden Fatah Palembang",
  "Universitas Islam Negeri Sunan Gunung Djati Bandung",
  "Universitas Islam Indonesia",
  "Universitas Muhammadiyah Yogyakarta",
  "Universitas Muhammadiyah Malang",
  "Universitas Muhammadiyah Surakarta",
  "Universitas Muhammadiyah Surabaya",
  "Universitas Muhammadiyah Jakarta",
  "Universitas Muhammadiyah Makassar",
  "Universitas Ahmad Dahlan",
  "Universitas AMIKOM Yogyakarta",
  "Universitas Dian Nuswantoro",
  "Universitas Stikubank",
  "Universitas Semarang",
  "Universitas 17 Agustus 1945 Surabaya",
  "Universitas Narotama",
  "Universitas Trunojoyo Madura",
  "Universitas PGRI Semarang",
  "Universitas PGRI Yogyakarta",
  "Universitas PGRI Madiun",
  "Sekolah Tinggi Ilmu Ekonomi Indonesia",
  "Sekolah Tinggi Akuntansi Negara",
  "Institut Teknologi dan Bisnis Ahmad Dahlan Jakarta",
  "Institut Bisnis dan Informatika Kwik Kian Gie",
  "Politeknik Negeri Jakarta",
  "Politeknik Negeri Bandung",
  "Politeknik Negeri Semarang",
  "Politeknik Negeri Surabaya",
  "Politeknik Negeri Malang",
  "Politeknik Negeri Medan",
  "Politeknik Negeri Bali",
  "Politeknik Negeri Ujung Pandang",
  "Politeknik Elektronika Negeri Surabaya",
  "Politeknik Manufaktur Bandung",
  "Akademi Angkatan Udara",
  "Akademi Angkatan Laut",
  "Akademi Militer",
  "Sekolah Tinggi Ilmu Kepolisian",
  "Institut Pemerintahan Dalam Negeri",

  // Major International Universities
  "Massachusetts Institute of Technology",
  "Stanford University",
  "Harvard University",
  "University of Cambridge",
  "University of Oxford",
  "California Institute of Technology",
  "ETH Zurich",
  "University of Chicago",
  "Imperial College London",
  "National University of Singapore",
  "Nanyang Technological University",
  "University of Tokyo",
  "Peking University",
  "Tsinghua University",
  "Seoul National University",
  "KAIST",
  "University of Melbourne",
  "University of Sydney",
  "University of Queensland",
  "Monash University",
  "University of British Columbia",
  "University of Toronto",
  "McGill University",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of Pennsylvania",
  "Cornell University",
  "University of Michigan",
  "University of California, Berkeley",
  "University of California, Los Angeles",
  "New York University",
  "Duke University",
  "Johns Hopkins University",
  "Northwestern University",
  "Carnegie Mellon University",
  "University of Edinburgh",
  "University College London",
  "King's College London",
  "London School of Economics",
  "Delft University of Technology",
  "Technical University of Munich",
  "Heidelberg University",
  "University of Amsterdam",
  "Leiden University",
  "Utrecht University",
  "Erasmus University Rotterdam",
  "University of Malaya",
  "Universiti Kebangsaan Malaysia",
  "Universiti Putra Malaysia",
  "Universiti Teknologi Malaysia",
  "Universiti Sains Malaysia",
  "Chulalongkorn University",
  "Mahidol University",
  "Ateneo de Manila University",
  "University of the Philippines",
  "De La Salle University",
  "University of Santo Tomas",
].sort();
